module.exports = {
    title: "Asset Allocation Planner",
    sliderInstructions: "To begin, select a risk profile from 1 to 10:",
    riskProfileLabel: "Currently selected:",
    chartTitle: "Your ideal asset allocation based on risk profile:",
    seriesName: "Percentage Allocation",
    largeCap: "Large Cap Stocks",
    midSmallCap: "Mid/Small Cap Stocks",
    international: "International Stocks",
    bonds: "Bonds",
    cash: "Cash",
    largeCapLabel: "Large Cap",
    midSmallCapLabel: "Mid/Small Cap",
    internationalLabel: "International",
    bondsLabel: "Bonds",
    cashLabel: "Cash",
    formTitle: "Enter your current asset allocation in the fields below:",
    currency: "$",
    conservative: "Conservative",
    aggressive: "Aggressive",
    nextSteps: "Next Steps",
    nextStepsSub: "To reach ideal allocation of assets, make the following transactions:",
    move: "Move",
    from: "from",
    to: "to",
    nextStepsInstructions: "Enter your current allocation of assets on the previous page.",
    noStepsText: "You have already achieved ideal allocation of assets. You do not need to take any additional steps.",
    sliderScreenTitle: "Asset Allocation Planner",
    chartScreenTitle: "Ideal Allocation",
    inputScreenTitle: "Current Allocation",
    stepsScreenTitle: "Next Steps",
    backButtonText: "Back",
    appInstructions: "This app will determine the your ideal allocation of assets based on the risk profile you choose. It will then determine the appropriate steps for you to take based off your current allocation of assets.",
    afterSliderInstructions: 'Once you have selected your risk profile, click "Next" to continue.',
    titlePartOne: "Asset",
    titlePartTwo: "Allocation",
    titlePartThree: "Planner"
};